apps/artigos/urls.py
from django.conf.urls import url
from django.contrib.auth.views import logout, login
from django.conf import settings

from . import views

app_name = 'artigo'

urlpatterns = [
    url(r'^lista-de-artigos/$', views.ArtigosView.as_view(), name='artigos'),
    url(r'^artigo/(?P<slug>[-\w]+)/$',views.ArtigosInternaView.as_view(), name='artigo-interno')
]

apps/contato/urls.py
from django.conf.urls import url
from django.contrib.auth.views import logout, login
from django.conf import settings

from . import views

app_name = 'contato'

urlpatterns = [
    url(r'^contato/$', views.ContatoCreateView.as_view(), name='contato'),
]

apps/grupo/urls.py
from django.conf.urls import url
from django.contrib.auth.views import logout, login
from django.conf import settings

from . import views

app_name = 'grupo'

urlpatterns = [
    url(r'^lista-de-grupos/$', views.GruposView.as_view(), name='grupos'),
    url(r'^criar-grupo/$', views.GruposCreateView.as_view(), name='criar-grupos'),
    url(r'^grupo/(?P<slug>[-\w]+)/$', views.GruposInternoView.as_view(), name='grupo'),
    url(r'^editar-grupo/(?P<slug>[-\w]+)/$', views.GruposEditView.as_view(), name='editar-grupo'),
    url(r'^delete-grupo/(?P<slug>[-\w]+)/$', views.GrupoDeleteView.as_view(), name='apagar-grupo'),
]

apps/usuario/urls.py
from django.conf.urls import url
from django.contrib.auth.views import logout, login
from django.conf import settings

from . import views

app_name = 'usuario'

urlpatterns = [
    url(r'^cadastro/$', views.SignUp.as_view(), name='signup'),
    url(r'^logout/', logout, {'next_page': 'website:home'}, name='logout'),
    url(r'^login/', views.LoginView.as_view(), name='login'),
    url(r'^perfil', views.update, name='perfil'),
    # url(r'^reset/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$', auth_views.password_reset_confirm, name='password_reset_confirm'),
    # url(r'^reset/done/$', auth_views.password_reset_complete, name='password_reset_complete'),
]

apps/website/urls.py
from django.conf.urls import url
from django.contrib.auth import views as auth_views
from apps.website.views import HomeView, QuemView, \
   ContatoView, ReceitasView, AreaView

app_name = 'website'

urlpatterns = [
    url(r'^$', HomeView.as_view(), name='home'),
]

principio_ativo/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf.urls.static import static
from django.conf import settings
from django.contrib.auth import views as auth_views

urlpatterns = [
    url(r'^manage-cms/', admin.site.urls),
    url(r'', include('apps.website.urls')),
    url(r'acesso/', include('apps.usuario.urls')),
    url(r'contato/', include('apps.contato.urls')),
    url(r'grupos/', include('apps.grupo.urls')),
    url(r'eventos/', include('apps.evento.urls')),
    url(r'artigos/', include('apps.artigos.urls')),
    url(r'^manage-cms/filemanager/', include('filemanager.urls', namespace='filemanager')),
    url(r'^tinymce/', include('tinymce.urls')),
    url(r'^reset-password/$', auth_views.password_reset, {'template_name': 'usuario/password_reset_form.html', 'post_reset_redirect': '/reset-password/done/'}, name='password_reset'),
    url(r'^reset-password/reset/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$', auth_views.password_reset_confirm, { 'template_name': 'usuario/password_reset_confirm.html'}, name='password_reset_confirm'),
    url(r'^reset-password/done/$', auth_views.password_reset_done, { 'template_name': 'usuario/password_reset_done.html' }, name='password_reset_done'),
    url(r'^reset-password/complete/$', auth_views.password_reset_complete, { 'template_name': 'usuario/password_reset_complete.html' }, name='password_reset_complete'),
    # url(r'^accounts/', include('django.contrib.auth.urls')),
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

apps/website/models.py
from django.db import models

from versatileimagefield.fields import VersatileImageField



class Banner(models.Model):
    nome = models.CharField(max_length=155)
    titulo = models.CharField(max_length=255, default="0")
    imagem = models.CharField(max_length=555, unique=False)
    ativo = models.BooleanField(default=False)

class BannerAnuncio(models.Model):
    nome = models.CharField(max_length=155)
    url = models.URLField(max_length=555, default="")
    imagem = models.CharField(max_length=555, unique=False)
    ativo = models.BooleanField(default=False)

class BannerBitcoin(models.Model):
    nome = models.CharField(max_length=155)
    url = models.URLField(max_length=555, default="")
    imagem = models.CharField(max_length=555, unique=False)
    ativo = models.BooleanField(default=False)

class Titulo(models.Model):
    titulo = models.CharField(max_length=255, default="0")
    Subtitulo = models.CharField(max_length=255, default="0")

apps/website/forms.py
from django import forms
from apps.receitas.models import Receitas
# from apps.receitas.models import UM_TRES


class ContatoForm(forms.Form):
    nome = forms.CharField(label="Nome",
                           widget=forms.TextInput(
                               attrs={'id': 'name',
                                      'type': 'text',
                                      'class': 'validate'}))
    email = forms.EmailField(label="Email",
                             widget=forms.TextInput(
                                 attrs={'id': 'email',
                                        'type': 'email',
                                        'class': 'validate'}))
    telefone = forms.CharField(label="Telefone",
                               widget=forms.TextInput(
                                   attrs={'id': 'fone',
                                          'type': 'text',
                                          'class': 'validate'}))
    cidade = forms.CharField(label="Telefone",
                               widget=forms.TextInput(
                                   attrs={'id': 'city',
                                          'type': 'text',
                                          'class': 'validate'}))
    observacoes = forms.CharField(label="Mensagem",
                               widget=forms.Textarea(
                                   attrs={'id': 'textarea1',
                                          'class': 'materialize-textarea'}))

class ReceitaForm(forms.ModelForm):

    class Meta:
        model = Receitas
        exclude = ('',)
        widgets = {
            'observacoes': forms.Textarea(attrs={'id': 'textarea1',
                                          'class': 'materialize-textarea'}),
            'alergia_texto': forms.Textarea(attrs={'id': 'textarea1',
                                          'class': 'materialize-textarea materialize-textarea gray'}),
            'descricao_objetivo': forms.Textarea(attrs={'id': 'textarea1',
                                          'class': 'materialize-textarea materialize-textarea gray'})
        }

class LoginForm(forms.Form):
    token = forms.CharField(widget=forms.TextInput(attrs={'type': 'password'}))

apps/website/views.py
from django.contrib.sites.shortcuts import get_current_site
from django.views.generic import TemplateView, ListView, FormView, DetailView
from django.db.models import Q
from django.http import HttpResponseRedirect
from django.core.mail import send_mail, EmailMessage
from django.conf import settings
from django.core.files.storage import FileSystemStorage

from apps.website.models import Banner, Titulo, BannerAnuncio, BannerBitcoin
from apps.website.forms import ContatoForm, ReceitaForm, LoginForm
from apps.sobre.models import Valores, Quem, Missao, Visao, ImagemQuemSomos
from apps.receitas.models import Receitas
from apps.grupo.models import Grupos


# Create your views here.
class HomeView(TemplateView):
    template_name = 'home.html'

    def get_context_data(self, **kwargs):
        context = super(HomeView, self).get_context_data(**kwargs)

        context.update(dict(
            banner_list=Banner.objects.filter(ativo=True)[:1],
            banner_anuncio_list=BannerAnuncio.objects.filter(ativo=True)[:1],
            banner_bitcoin_list=BannerBitcoin.objects.filter(ativo=True)[:1],
            grupos_list=Grupos.objects.all(),
            titulo=Titulo.objects.all()[:1]
        ))
        return context


# class LoginView(FormView):
#     template_name = 'login.html'
#     form_class = LoginForm
#     success_url = '/area'

#     def form_valid(self, form, **kwargs):
#         print('Form valido')
#         token_try = form.cleaned_data['token']
#         token_check = pro_models.Token.objects.filter(token=token_try)
#         if token_check.exists():
#             self.request.session["token_active"] = True
#         else:
#             return self.form_invalid(form)
#         return HttpResponseRedirect(self.get_success_url())

#     def form_invalid(self, form, **kwargs):
#         print('Form invalido')
#         context = super(LoginView, self).get_context_data(**kwargs)
#         # send_mail()
#         context['message_err'] = 'O token digitado é invalido'
#         return self.render_to_response(context)


class QuemView(TemplateView):
    template_name = 'quem.html'

    def get_context_data(self, **kwargs):
        context = super(QuemView, self).get_context_data(**kwargs)

        context.update(dict(
            missao=Missao.objects.filter(ativo=True).last(),
            quem=Quem.objects.filter(ativo=True).last(),
            visao=Visao.objects.filter(ativo=True).last(),
            valores=Valores.objects.filter(ativo=True)[:6],
            imagem_quem=ImagemQuemSomos.objects.filter(ativo=True).last()
        ))
        return context


class AreaView(ListView):
    template_name = 'area.html'

    def get_context_data(self, **kwargs):
        context = super(AreaView, self).get_context_data(**kwargs)
        context['categoria_list'] = pro_models.Categoria.objects.all()
        return context

    def find_categoria(self, cat_name):
        return pro_models.Categoria.objects.filter(nome_categoria=cat_name)

    def dispatch(self, request, *args, **kwargs):
        token_check = request.session.get('token_active', False)
        if not token_check:
            return HttpResponseRedirect('/login/')
        return super(AreaView, self).dispatch(request, *args, **kwargs)

    def get_queryset(self):
        search = self.request.GET.get('search', None)
        cat = self.request.GET.get('cat', None)
        if search:
            return pro_models.Pdf.objects.filter(
                (Q(titulo__icontains=search) |
                 Q(categoria_fk__nome_categoria__icontains=search)))
        elif cat:
            return pro_models.Pdf.objects.filter(
                categoria_fk=self.find_categoria(cat))
        return pro_models.Pdf.objects.all()


class ContatoView(FormView):
    template_name = 'contato.html'
    form_class = ContatoForm
    sucess_url = '/contato'

    def form_valid(self, form, **kwargs):
        # print('Form valido')
        context = super(ContatoView, self).get_context_data(**kwargs)
        email_content = ''
        for field, val in form.cleaned_data.items():
            if val:
                email_content += '\n{}: {}'.format(field.title(), val)

        send_mail(
            'Contato - %s' % (form.cleaned_data['nome']), email_content,
            'tester@gmail.com',
            ['tester@gmail.com'], fail_silently=False,
        )
        # print('nome', form.cleaned_data['nome'])
        # send_mail()
        context['message'] = 'Mensagem enviada com sucesso!'
        return self.render_to_response(context)

    def form_invalid(self, form, **kwargs):
        # print('Form invalido')
        context = super(ContatoView, self).get_context_data(**kwargs)
        # print('nome', form.cleaned_data['nome'])
        context['message_err'] = 'Preencha todos os campos corretamente'
        return self.render_to_response(context)


class ReceitasView(FormView):
    template_name = 'receitas.html'
    form_class = ReceitaForm
    sucess_url = '/receitas'

    def form_valid(self, form, **kwargs):
        context = super(ReceitasView, self).get_context_data(**kwargs)
        data = form.save()
        url = Receitas.objects.last()
        email_list = [
            'tester@gmail.com'
        ]
        email = email_list[0]

        email_content, i = '', 0
        for field, val in form.cleaned_data.items():
            if val and field != 'receita':
                format_field = data._meta.get_field(field).verbose_name
                email_content += '\n{}: {}'.format(format_field.title(), val)
            elif field == 'receita':
                url = get_current_site(self.request).domain
                email_content += '\n{0}: http://{1}{2}'.format(
                    field.title(), url, data.receita.url,
                )
            if i >= 7 and val:
                email = email_list[0]
            i += 1
        try:
            email_content += '\nReceita1 Link: {}'.format('http://principioativo.far.br' + url.receita1.url)
            email_content += '\nReceita2 Link: {}'.format('http://principioativo.far.br' + url.receita2.url)
            email_content += '\nReceita3 Link: {}'.format('http://principioativo.far.br' + url.receita3.url)
        except:
            print('não tem todas as receitas')

        send_mail(
            'Nova Receita - %s' % (form.cleaned_data['nome']), email_content,
            'tester@gmail.com',
            [email], fail_silently=False,
        )
        # orcamento@principiotivo.far.br
        context['message'] = 'Mensagem enviada com sucesso!'
        return self.render_to_response(context)

    def form_invalid(self, form, **kwargs):
        context = super(ReceitasView, self).get_context_data(**kwargs)
        context['message_err'] = 'Preencha todos os campos corretamente'
        return self.render_to_response(context)

apps/website/templates/components/base.html
{% load staticfiles %}

<!DOCTYPE html>
<html lang="pt-BR">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=no">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/css/materialize.min.css">
  <link rel="stylesheet" href="{% static 'css/app.css' %}" media="screen">
  <script src="{% static 'js/dist/app.js' %}" charset="utf-8"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/js/materialize.min.js"></script>
  <title>Direita Unida {% block title %}{% endblock %}</title>
  <link rel="shortcut icon" href="{% static 'img/logos.png' %}" />
  <meta name="theme-color" content="#ffffff">
  <meta name="keywords" content="Direita Unida, direita, união" />
  <meta name="description" content="Direita unida, a união faz a força" />
  <meta name="msapplication-TileColor" content="#ffffff">
  <meta name="msapplication-TileImage" content="{% static 'img/logos.png' %}">
</head>
<body>

  <nav class="transpar">
    <div class="nav-wrapper flexin">
      <a href="{% url 'website:home' %}" class="brand-logo center">
        <img src="{% static 'img/logos.png' %}" alt="" class="logo">
      </a>
      <a href="#" data-target="slide-out" class="sidenav-trigger">
        <i class="material-icons">menu</i>
      </a>
      <ul class="left hide-on-med-and-down arm">
        <li><a href="/" class="color-gray">
          Home
        </a></li>
        <li>
          <a href="{% url 'grupo:grupos' %}" class="color-gray {% if request.resolver_match.url_name == "grupos"%}active{% endif %}">
            Grupos
          </a>
        </li>
        <li>
          <a href="/eventos/lista-de-eventos/" class="color-gray">
            Eventos
          </a>
        </li>
      </ul>
      <ul class="right hide-on-med-and-down arm">
          <li>
            <a href="{% url 'artigo:artigos' %}" class="color-gray">
              Artigos
            </a>
          </li>
          <li>
            <a href="{% url 'contato:contato' %}" class="color-gray">
              Contato
            </a>
          </li>
          <li>
            {% if user.is_authenticated %}
            <a class='dropdown-trigger color-gray outline' href='#' data-target='dropdown1'>Menu</a>
            <ul id='dropdown1' class='dropdown-content'>
              <li>
                <a class="color-gray" href="{% url 'usuario:perfil' %}"> Perfil </a>
              </li>
              <li>
                <a class="color-gray" href="{% url 'usuario:logout' %}"> Sair </a>
              </li>
            </ul>

            {% else %}
              <a href="{% url 'usuario:login' %}" class="color-gray {% if request.resolver_match.url_name == "login"%}active{% endif %}">
                Acesso
              </a>
              {% comment %} <a href="{% url 'password_reset' %}">recuperar</a> {% endcomment %}
            {% endif %}
          </li>
      </ul>
      <ul id="slide-out" class="sidenav">
        <li><a href="/" class="color-gray">Home</a></li>
        <li><a href="{% url 'grupo:grupos' %}" class="color-gray ">Grupos</a></li>
        <li><a href="/eventos/lista-de-eventos/" class="color-gray">Eventos</a></li>
        <li><a href="{% url 'artigo:artigos' %}" class="color-gray">Artigos</a></li>
        <li><a href="{% url 'contato:contato' %}" class="color-gray">Contato</a></li>
        <li>
          {% if user.is_authenticated %}
          <a class='dropdown-trigger color-gray outline' href='#' data-target='dropdown2'>Menu</a>
          <ul id='dropdown2' class='dropdown-content'>
            <li>
              <a class="color-gray" href="{% url 'usuario:perfil' %}"> Perfil </a>
            </li>
            <li>
              <a class="color-gray" href="{% url 'usuario:logout' %}"> Sair </a>
            </li>
          </ul>

          {% else %}
            <a href="{% url 'usuario:login' %}" class="color-gray {% if request.resolver_match.url_name == "login"%}active{% endif %}">
              Acesso
            </a>
          {% endif %}
        </li>
      </ul>
    </div>
  </nav>
  <div class="content" >
    {% block content %}

    {% endblock %}
  </div>
  <footer class="background-black">
    <div class="col m6">
      <p class="color-white">
        © Copyright Direita Unida 2019. Todos os direitos reservados.
      </p>
    </div>
    <div class="col m6">
      <a href="https://github.com/Filip3Dev" target="_blank">
        <img src="https://avatars1.githubusercontent.com/u/19575298?s=460&v=4" alt="" width="30" title="Feito com carinho por Filipe Machado"/>
      </a>
    </div>
  </footer>
  <script>
    $('.dropdown-trigger').dropdown({
      coverTrigger: false
    });
  </script>
  {% block extra_js %}
  {% endblock %}
  <!-- ANALITICS -->
</body>
</html>

apps/website/templates/components/base2.html
<!DOCTYPE html>
<html lang="pt-BR">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=no">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.98.0/css/materialize.min.css">
  <link rel="stylesheet" href="../static/css/app.css" media="screen">
  <script src="../static/js/dist/app.js" charset="utf-8"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.98.0/js/materialize.min.js"></script>
  <title>Principio Ativo</title>
</head>
<body class="tips-back">
  <div class="" style="min-height: 100%; position: relative;">
    <nav class="background-white area-nav esx">
        <div class="nav-wrapper">
          <a href="{% url 'website:home' %}" class="brand-logo center">
            <img src="../static/img/logo.png" alt="" class="logo">
          </a>
          <a href="#" data-activates="mobile-demo" class="button-collapse">
            <i class="material-icons">menu</i>
          </a>
          <ul class="side-nav" id="mobile-demo">
          <li><a href="{% url 'website:lojas' %}" class="color-gray">Nossas Lojas</a></li>
          <li><a href="{% url 'website:quem-somos' %}" class="color-gray">Quem Somos</a></li>
          <li><a href="{% url 'website:produtos' %}" class="color-gray">Produtos</a></li>
          <li><a href="{% url 'website:receitas' %}" class="color-gray">Orçamento</a></li>
          <li><a href="{% url 'website:saude' %}" class="color-gray">Dicas de Saúde</a></li>
          <li><a href="{% url 'website:contato' %}" class="color-gray">Fale Conosco</a></li>
          </ul>
        </div>
      </nav>
  {% block content %}

  {% endblock %}
  </div>
  <!-- <footer class="background-black anex">
    <div class="col m6">
      <p class="color-white">
        © Copyright Principio Ativo 2017. Todos os direitos reservados.
      </p>
    </div>
    <div class="col m6">
      <a href="http://128bits.cc/">
        <img src="http://www.pi.senac.br/static/frontend/img/128bits.png" alt="" />
      </a>
    </div>
  </footer> -->
  <script>
    (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
    (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
    m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
    })(window,document,'script','https://www.google-analytics.com/analytics.js','ga');

    ga('create', 'UA-97520637-1', 'auto');
    ga('send', 'pageview');

  </script>
</body>
</html>

apps/website/templates/components/base3.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="pt-BR">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=no">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.98.0/css/materialize.min.css">
  <link rel="stylesheet" href="{% static 'css/app.css' %}" media="screen">
  <script src="{% static 'js/dist/app.js' %}" charset="utf-8"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.98.0/js/materialize.min.js"></script>
  <title>
    {% block title %}{% endblock title %}                                               
  </title>
</head>
<body class="tips-back">
  <div class="" style="min-height: 100%; position: relative;">

  {% block content %}

  {% endblock %}
  </div>
  <script>
    (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
    (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
    m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
    })(window,document,'script','https://www.google-analytics.com/analytics.js','ga');

    ga('create', 'UA-97520637-1', 'auto');
    ga('send', 'pageview');

  </script>
</body>
</html>