apps/artigos/urls.py
from django.conf.urls import url
from django.contrib.auth.views import logout, login
from django.conf import settings

from . import views

app_name = 'artigo'

urlpatterns = [
    url(r'^lista-de-artigos/$', views.ArtigosView.as_view(), name='artigos'),
    url(r'^artigo/(?P<slug>[-\w]+)/$',views.ArtigosInternaView.as_view(), name='artigo-interno')
]

apps/contato/urls.py
from django.conf.urls import url
from django.contrib.auth.views import logout, login
from django.conf import settings

from . import views

app_name = 'contato'

urlpatterns = [
    url(r'^contato/$', views.ContatoCreateView.as_view(), name='contato'),
]

apps/evento/urls.py
from django.conf.urls import url
from django.contrib.auth.views import logout, login
from django.conf import settings

from . import views

app_name = 'evento'

urlpatterns = [
    url(r'^lista-de-eventos/$', views.EventoView.as_view(), name='eventos'),
    url(r'^evento/(?P<slug>[-\w]+)/$', views.EventoInternoView.as_view(), name='evento'),
    url(r'^criar-evento/$', views.EventoCreateView.as_view(), name='criar-evento'),
    url(r'^editar-evento/(?P<slug>[-\w]+)/$', views.EventoEditView.as_view(), name='editar-evento'),
    url(r'^delete-evento/(?P<slug>[-\w]+)/$', views.EventoDeleteView.as_view(), name='apagar-evento'),
]

apps/grupo/urls.py
from django.conf.urls import url
from django.contrib.auth.views import logout, login
from django.conf import settings

from . import views

app_name = 'grupo'

urlpatterns = [
    url(r'^lista-de-grupos/$', views.GruposView.as_view(), name='grupos'),
    url(r'^criar-grupo/$', views.GruposCreateView.as_view(), name='criar-grupos'),
    url(r'^grupo/(?P<slug>[-\w]+)/$', views.GruposInternoView.as_view(), name='grupo'),
    url(r'^editar-grupo/(?P<slug>[-\w]+)/$', views.GruposEditView.as_view(), name='editar-grupo'),
    url(r'^delete-grupo/(?P<slug>[-\w]+)/$', views.GrupoDeleteView.as_view(), name='apagar-grupo'),
]

principio_ativo/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf.urls.static import static
from django.conf import settings
from django.contrib.auth import views as auth_views

urlpatterns = [
    url(r'^manage-cms/', admin.site.urls),
    url(r'', include('apps.website.urls')),
    url(r'acesso/', include('apps.usuario.urls')),
    url(r'contato/', include('apps.contato.urls')),
    url(r'grupos/', include('apps.grupo.urls')),
    url(r'eventos/', include('apps.evento.urls')),
    url(r'artigos/', include('apps.artigos.urls')),
    url(r'^manage-cms/filemanager/', include('filemanager.urls', namespace='filemanager')),
    url(r'^tinymce/', include('tinymce.urls')),
    url(r'^reset-password/$', auth_views.password_reset, {'template_name': 'usuario/password_reset_form.html', 'post_reset_redirect': '/reset-password/done/'}, name='password_reset'),
    url(r'^reset-password/reset/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$', auth_views.password_reset_confirm, { 'template_name': 'usuario/password_reset_confirm.html'}, name='password_reset_confirm'),
    url(r'^reset-password/done/$', auth_views.password_reset_done, { 'template_name': 'usuario/password_reset_done.html' }, name='password_reset_done'),
    url(r'^reset-password/complete/$', auth_views.password_reset_complete, { 'template_name': 'usuario/password_reset_complete.html' }, name='password_reset_complete'),
    # url(r'^accounts/', include('django.contrib.auth.urls')),
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

apps/contato/models.py
from django.db import models

# Create your models here.
class Contato(models.Model):
  nome = models.CharField('Nome', max_length=255, null=False, blank=False, default='')
  email = models.EmailField('E-mail', max_length=70, unique=False)
  texto = models.TextField('Texto', max_length=600, null=False, blank=False)
  status = models.BooleanField("Lida", default=False)
  criado_em = models.DateTimeField(blank=True, auto_now_add=True)
  alterado_em = models.DateTimeField(blank=True, auto_now=True)

  class Meta:
    verbose_name = 'Contato'
    verbose_name_plural = 'Contatos'

  def __str__(self):
    return '{}'.format(self.nome)

apps/grupo/models.py
from django.db import models
import random
import datetime
from apps.usuario.models import Usuario
from django.utils.text import slugify
from random import randrange

class Grupos(models.Model):

    nome = models.CharField(max_length=355, null=True, blank=True)
    descricao = models.CharField(max_length=355, null=True, blank=True)
    categoria = models.CharField(max_length=355, null=True, blank=True)
    subcategoria = models.CharField(max_length=355, null=True, blank=True)
    lat = models.CharField(max_length=355, null=True, blank=True)
    lon = models.CharField(max_length=355, null=True, blank=True)
    estado = models.CharField(max_length=355, null=True, blank=True, default='nao_informado')
    endereco = models.CharField(max_length=355, null=True, blank=True)
    telefone = models.CharField(max_length=355, null=True, blank=True)
    email = models.EmailField(null=True, blank=True)
    codigo = models.CharField(max_length=355, null=True, blank=True)
    creation_user = models.ForeignKey(Usuario, on_delete=models.PROTECT, related_name='creation', verbose_name='Usuário Inclusão')
    slug = models.SlugField(max_length=700)

    plataforma1 = models.CharField(max_length=355, null=True, blank=True)
    link1 = models.CharField(max_length=355, null=True, blank=True)
    plataforma2 = models.CharField(max_length=355, null=True, blank=True)
    link2 = models.CharField(max_length=355, null=True, blank=True)
    plataforma3 = models.CharField(max_length=355, null=True, blank=True)
    link3 = models.CharField(max_length=355, null=True, blank=True)
    plataforma4 = models.CharField(max_length=355, null=True, blank=True)
    link4 = models.CharField(max_length=355, null=True, blank=True)
    plataforma5 = models.CharField(max_length=355, null=True, blank=True)
    link5 = models.CharField(max_length=355, null=True, blank=True)
    criado_em = models.DateTimeField(
        verbose_name='Criado em', auto_now_add=True)
    modificado_em = models.DateTimeField(
        verbose_name='Modificado em', auto_now=True)

    class Meta:
        verbose_name = "Grupo"
        verbose_name_plural = "Grupos"

    def save(self, *args, **kwargs):
        self.codigo = random.getrandbits(128)
        self.slug = slugify(self.nome)
        while True:
            noticia = Grupos.objects.filter(slug=self.slug)
            if noticia.exists():
                self.slug = '{}{}'.format(self.slug, randrange(10000000000))
            else:
                break
        super(Grupos, self).save(*args, **kwargs)

apps/contato/forms.py
from django import forms
from apps.contato.models import Contato
import requests


class ContactForm(forms.ModelForm):
  class Meta:
    model = Contato
    fields = ('nome', 'email', 'texto')

apps/evento/forms.py
from django import forms
from .models import *
from django.forms import ModelForm


class EventoscreateForm(ModelForm):
    class Meta:
        model = Evento
        exclude = ('creation_user', 'slug')

apps/grupo/forms.py
from django import forms
from .models import *
from django.forms import ModelForm

class GruposcreateForm(ModelForm):
    class Meta:
        model = Grupos
        exclude = ('codigo', 'creation_user', 'slug')

apps/usuario/forms.py
from django import forms
from captcha.fields import ReCaptchaField
from captcha.widgets import ReCaptchaV2Checkbox
from django.contrib.auth.forms import UserCreationForm, UserChangeForm
from .models import *
from django.forms import ModelForm


class CustomUserCreationForm(UserCreationForm):
    class Meta:
        model = Usuario
        captcha = ReCaptchaField(widget=ReCaptchaV2Checkbox(
            attrs={
                'data-theme': 'dark',
                'data-size': 'compact',
            }
        ))
        fields = ['nome', 'username', 'email', 'estado_usuario', 'cidade_usuario']


class CustomUserChangeForm(ModelForm):
    class Meta:
        model = Usuario
        fields = ['nome', 'username', 'email',
                'estado_usuario', 'cidade_usuario']
    cidade_usuario = forms.CharField(label="Cidade", widget=forms.TextInput(
        attrs={'id': 'cidade_usuario', 'type': 'text', 'class': 'validate'}))
    username = forms.CharField(label="Apelido", widget=forms.TextInput(
        attrs={'id': 'username', 'type': 'text', 'class': 'validate'}))
    nome = forms.CharField(label="Nome", widget=forms.TextInput(
        attrs={'id': 'nome', 'type': 'text', 'class': 'validate'}))
    email = forms.EmailField(label="Email", widget=forms.TextInput(
        attrs={'id': 'email', 'type': 'email', 'class': 'validate'}))
class LoginForm(forms.Form):
    email = forms.EmailField(label="Email", widget=forms.TextInput( attrs={'id': 'email', 'type': 'email', 'class': 'validate'}))
    password = forms.CharField(label="Senha", widget=forms.TextInput(attrs={'type': 'password'}))
class RecoverForm(forms.Form):
    email = forms.EmailField(label="Email", widget=forms.TextInput( attrs={'id': 'email', 'type': 'email', 'class': 'validate'}))

apps/contato/views.py
import json
import urllib
from django.views import generic
from django.contrib import messages
from django.core.urlresolvers import reverse_lazy
from django.contrib.auth import login, authenticate
from django.contrib.auth.decorators import login_required
from django.utils.decorators import method_decorator
from django.views.generic import TemplateView, ListView, FormView, DetailView, DeleteView
from django.views.generic.edit import UpdateView
from django.conf.urls import url
from django.shortcuts import render, redirect, render_to_response
from django.template import RequestContext
from .models import *
from .forms import ContactForm
from django.http import HttpResponseRedirect, Http404
from django.contrib.auth.mixins import LoginRequiredMixin
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.core.mail import send_mail, EmailMessage
from django.conf import settings
import telegram


# Create your views here.


class ContatoCreateView(generic.CreateView):
    model = Contato
    form_class = ContactForm
    template_name = 'contato_create.html'

    def form_valid(self, form):
        recaptcha_response = self.request.POST.get('g-recaptcha-response')
        url = 'https://www.google.com/recaptcha/api/siteverify'
        values = {
            'secret': settings.RECAPTCHA_PRIVATE_KEY,
            'response': recaptcha_response
        }
        data = urllib.parse.urlencode(values).encode()
        req =  urllib.request.Request(url, data=data)
        response = urllib.request.urlopen(req)
        result = json.loads(response.read().decode())

        if result['success']:
            obj = form.save(commit=False)
            obj.save()
            messages.success(self.request, 'Contato salvo com sucesso')
            email_content = 'Novo cadastro de CONTATO '
            email_content += '\nNome: {}'.format(form.cleaned_data['nome'])
            email_content += '\nEmail: {}'.format(form.cleaned_data['email'])
            email_content += '\nTexto: {}'.format(form.cleaned_data['texto'])
            bot = telegram.Bot('752881370:AAHKmpMXALAUzt1d89UUvoCkayq5GPXqO0Y')
            chat_id = -1001440430219
            try:
                bot.send_message(chat_id=chat_id, text=email_content)
                pass
            except Exception as e:
                print(e)
                pass

            return redirect('contato:contato')
        else:
            messages.error(self.request, 'reCAPTCHA invalida. Tente novamente.')
            return render(self.request, 'contato_create.html', {'form': form})

    def form_invalid(self, form):
        print(form)
        return render(self.request, 'contato_create.html', {'form': form})

apps/evento/views.py
from django.views import generic
from django.contrib import messages
from django.core.urlresolvers import reverse_lazy
from django.contrib.auth import login, authenticate
from django.contrib.auth.decorators import login_required
from django.utils.decorators import method_decorator
from django.views.generic import TemplateView, ListView, FormView, DetailView, DeleteView
from django.views.generic.edit import UpdateView
from django.conf.urls import url
from django.shortcuts import render, redirect, render_to_response
from django.template import RequestContext
from .models import *
from .forms import EventoscreateForm
from django.http import HttpResponseRedirect, Http404
from django.contrib.auth.mixins import LoginRequiredMixin
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.core.mail import send_mail, EmailMessage
from django.conf import settings
import telegram

# Create your views here.

class EventoView(ListView):
  template_name = 'eventos.html'
  model = Evento
  paginate_by = 5
  context_object_name = 'eventos_list'

  def get_context_data(self, **kwargs):
        qs = Evento.objects.all().order_by('-criado_em')

        keyword1 = self.request.GET.get('estado')
        keyword2 = self.request.GET.get('titulo')
        if keyword1:
            qs = Evento.objects.filter(estado__icontains=keyword1)
            context = super(EventoView, self).get_context_data(**kwargs)
            if str(self.request.user) == "AnonymousUser":
                user_loged = False
                pass
            else:
                user_loged = True
                pass
            context.update(dict(
                eventos_list=qs,
                user_loged=user_loged
            ))
            return context
        if keyword2:
            qs = Evento.objects.filter(titulo__icontains=keyword2)
            context = super(EventoView, self).get_context_data(**kwargs)
            if str(self.request.user) == "AnonymousUser":
                user_loged = False
                pass
            else:
                user_loged = True
                pass
            context.update(dict(
                eventos_list=qs,
                user_loged=user_loged
            ))
            return context

        context = super(EventoView, self).get_context_data(**kwargs)
        if str(self.request.user) == "AnonymousUser":
            user_loged = False
            pass
        else:
            user_loged = True
            pass
        context.update(dict(
            eventos_list=qs,
            user_loged=user_loged
        ))
        return context


class EventoInternoView(LoginRequiredMixin, DetailView):
    login_url = '/acesso/login/?needlogin=true'
    template_name = 'evento.html'

    model = Evento

    def get_context_data(self, **kwargs):
        context = super(EventoInternoView, self).get_context_data(**kwargs)

        context.update(dict(
            noticias_list=Evento.objects.all().order_by("-criado_em"),
        ))

        return context


class EventoCreateView(LoginRequiredMixin, generic.CreateView):
    login_url = '/acesso/login/?needlogin=true'
    model = Evento
    form_class = EventoscreateForm
    template_name = 'evento_create.html'

    def form_valid(self, form):
        obj = form.save(commit=False)
        obj.creation_user = self.request.user
        obj.save()
        messages.success(self.request, 'Evento criado com sucesso')
        email_content = 'Novo cadastro de EVENTO '
        email_content += '\nTitulo: {}'.format(form.cleaned_data['titulo'])
        email_content += '\nInicio: {}'.format(form.cleaned_data['inicio'])
        email_content += '\nEstado: {}'.format(form.cleaned_data['estado'])
        bot = telegram.Bot('752881370:AAHKmpMXALAUzt1d89UUvoCkayq5GPXqO0Y')
        chat_id = -1001440430219
        try:
            bot.send_message(chat_id=chat_id, text=email_content)
            pass
        except Exception as e:
            print(e)
            pass
        return redirect('evento:eventos')

    def form_invalid(self, form):
        print(form)
        return render(self.request, 'evento_create.html', {'form': form})


class EventoEditView(LoginRequiredMixin, UpdateView):
    login_url = '/acesso/login/?needlogin=true'
    template_name = 'evento_edit.html'
    form_class = EventoscreateForm
    model = Evento

    def form_valid(self, form):
        obj = form.save(commit=False)
        obj.save()
        messages.success(self.request, 'Evento editado com sucesso')
        return redirect('evento:eventos')

class EventoDeleteView(LoginRequiredMixin, DeleteView):
    login_url = '/acesso/login/?needlogin=true'
    template_name = 'evento_confirm_delete.html'
    success_url = '/eventos/lista-de-eventos/'
    model = Evento

    def get_object(self, queryset=None):
        obj = super(EventoDeleteView, self).get_object()
        if not obj.creation_user == self.request.user:
            raise Http404
        return obj

apps/receitas/views.py
from django.shortcuts import render

# Create your views here.

apps/website/templates/contato_create.html
<!-- templates/signup.html -->
{% extends 'components/base.html' %}
{% include 'material/includes/material_css.html' %}
{% include 'material/includes/material_js.html' %}
{% load materialize %}

{% block title %}Cadastro{% endblock %}

{% block content %}
<style>
  /* Always set the map height explicitly to define the size of the div
       * element that contains the map. */
  .formerCadastro{
    width: 70%;
    margin: 0 auto;
  }
  
  #map {
    height: 100%;
  }

  /* Optional: Makes the sample page fill the window. */
  html,
  body {
    height: 100%;
    margin: 0;
    padding: 0;
  }
  .listContact{
    margin: 0px;
  }
  .listContact li{
    display: flex;
    align-items: center;
    margin-bottom: 8px;
  }
  .listContact li p{
    margin: 0px;
    margin-left: 8px;
  }
  .listContact li a{
    width: 25px;
  }
  .listContact li a img{
    width: 25px;
  }
  .g-recaptcha > div{
    margin: 0px auto;
  }
  .warn{
    color: red;
  }
</style>
<div class="container">
  <div class="row expanded">
    <br>
    <div class="col s12 m12 l12">
      <br>
      <h4 class="center">
        Entre em contato conosco
      </h4>
      <div class="divider"></div>
    </div>
  </div>
  <div class="row expanded">
    <div>
      {% if messages %}
        {% for message in messages %}
          <p class="warn">
            {{message}}
          </p>
        {% endfor %}
      {% endif %}
    </div>
    <form method="post" class="formerCadastro">
      {% csrf_token %}
      <div class="row">
        <div class="input-field col s12">
          {{ form.nome.errors }}
          {{ form.nome }}
          <label for="id_nome" class="">
            Digite seu nome
          </label>
        </div>
        <div class="input-field col s12 m12">
          {{ form.email.errors }}
          {{ form.email }}
          <label for="id_email" class="">
            Email para contato
          </label>
        </div>
        <div class="input-field col s12 m12">
          {{ form.texto.errors }}
          <textarea id="id_texto" name="texto" class="materialize-textarea" rows="4" cols="50"></textarea>
          <label for="id_texto" class="">
            Digite sua mensagem
          </label>
        </div>
      </div>
      <div class="row">
        <div class="col s12">
          <script src='https://www.google.com/recaptcha/api.js'></script>
          <div class="g-recaptcha" data-sitekey="6LffQvcUAAAAABnqV0c1P4QB7z215v9ETHkABqVS"></div>
        </div>
      </div>
      
      <div class="row">
        <div class="col s6">
          <div>
            <ul class="listContact">
              <li>
                <a href="mailto:contato@direita-unida.com" target="_blank" rel="noopener noreferrer">
                  <img src="https://image.flaticon.com/icons/svg/732/732200.svg" alt="">
                </a>
                <p>
                  contato@direita-unida.com
                </p>
              </li>
              <li>
                <a href="https://t.me/joinchat/IB8rU0o4nqskaBQ-IvSqog" target="_blank" rel="noopener noreferrer">
                  <img src="https://image.flaticon.com/icons/svg/185/185977.svg" alt="">
                </a>
                <p>
                  Telegram
                </p>
              </li>
            </ul>
          </div>
        </div>
        <div class="col s6 center-align">
          <button type="submit" name="button" class="waves-effect waves-light btn">
            Enviar mensagem
            <i class="material-icons right">send</i>
          </button>
        </div>
      </div>
    </form>
  </div>
</div>

<script src="https://cdn.jsdelivr.net/npm/jquery-mask-plugin@1.14.15/dist/jquery.mask.min.js"></script>
<script>
  
</script>
<script>
  $(document).ready(function () {
    $('select').formSelect();
    $('#id_telefone').mask('(00) 00000-0000');
  });

</script>
{% endblock %}

apps/website/templates/evento.html
<!-- templates/signup.html -->
{% extends 'components/base.html' %}
{% include 'material/includes/material_css.html' %}
{% include 'material/includes/material_js.html' %}
{% load materialize %}

{% block title %}Cadastro{% endblock %}

{% block content %}
<style>
  .flexmap{
    display: flex;
    align-items: center;
    justify-content: center;
    max-width: 100%;
    max-height: 100%;
  }
  #map {
    height: 100%;
    padding: 50%;
    border: none;
  }

  /* Optional: Makes the sample page fill the window. */
  html,
  body {
    height: 100%;
    margin: 0;
    padding: 0;
  }
  .goLink{
    display: flex;
    align-items: center;
  }
  .goLink i{
    margin-left: 8px;
  }
  .address{
    display: flex;
    align-items: center;
    justify-content: space-between;
  }
</style>
<div class="container">
  <div class="row">
    <div class="col s12 m12 l12">
      <br>
      <h4 class="center" id="topo">
        {{object.titulo}}
      </h4>
      <div class="divider"></div>
    </div>
    <div class="col s12 m12 l12">
      <div class="row">
        <div class="col s12 m12 l12">
          <div>
            <br>
            <h6 class="">
              <b>
                Descrição
              </b>
            </h6>
            <h6 class="">
              {{object.descricao}}
            </h6>
          </div>
          <br>
        </div>
        <div class="col s12 m6 l6">
          <div>
            <h6>
              <b>
                Data do evento
              </b>
            </h6>
            <h6 class="">
              {{object.inicio}}
            </h6>
          </div>
        </div>
        <div class="col s12 m6 l6">
          <div>
            <h6>
              <b>
                Link promocional do evento
              </b>
            </h6>
            <h6 class="">
              <a href="{{object.link}}" class="goLink" target="_blank">
                Acessar o link
                <i class="material-icons">launch</i>
              </a>
            </h6>
          </div>
          <br>
        </div>
        <div class="col s12 m12 l12">
          <div>
            <h6>
              <b>
                Endereço do evento
              </b>
            </h6>
            <h6 class="address">
              {{object.endereco}}
              <a href="http://www.google.com/maps/place/{{ object.lat }},{{ object.lon }}" class="goLink" target="_blank">
                Navegar
                <i class="material-icons">launch</i>
              </a>
            </h6>
          </div>
        </div>
        
        <div class="col s12 m12 l12">
          <div class="card">
            <div class="card-content mapView">
              <div class="flexmap">
                <div id="map" class="mobile"></div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
  <div class="row">
    {% if object.creation_user == user %}
      <div class="col s12 m12 l12 center">
        <div class="fixed-action-btn">
          <a class="btn-floating btn-large red">
            <i class="large material-icons">menu</i>
          </a>
          <ul>
            <li>
              <a href="/eventos/delete-evento/{{object.slug}}" class="btn-floating black darken-1">
                <i class="material-icons">delete</i>
              </a>
            </li>
            <li><a class="btn-floating red" href="/eventos/criar-evento/"><i class="material-icons">add_circle</i></a></li>
            <li><a href="/eventos/editar-evento/{{object.slug}}" class="btn-floating yellow darken-1"><i class="material-icons">create</i></a></li>
          </ul>
        </div>
      </div>
    {% else %}
      <div class="col s12 m12 l12 center">
        <a class="waves-effect waves-light btn floater" href="{% url 'evento:criar-evento' %}">
          Criar evento
        </a>
      </div>
    {% endif %}
  </div>
</div>

<script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyDBTxe7umFpRdN0Gf7N0vY5j4clM69Pceg&callback=initMap" async defer></script>
<script>
  $(document).ready(function () {
    $('.fixed-action-btn').floatingActionButton();
    $('.collapsible').collapsible();
    $('.modal').modal();
    setTimeout(function () { openSolution({{ object.lat }}, {{ object.lon }}) }, 2000);
  });
  function openSolution(lat, long) {
    let geocoder = new google.maps.Geocoder;
    let infoWindow = new google.maps.InfoWindow;
    let home = { lat: lat, lng: long };
    geocodeLatLng(geocoder, map, infoWindow, home);
  }
  var map, infoWindow;
  function initMap() {
    map = new google.maps.Map(document.getElementById('map'), {
      center: { lat: {{ object.lat }}, lng: {{ object.lon }} },
      zoom: 10,
      disableDefaultUI: true,
      zoomControl: true,
      styles: [{
        featureType: 'poi',
        stylers: [{ visibility: 'off' }]  // Turn off points of interest.
      }, {
        featureType: 'transit.station',
        stylers: [{ visibility: 'off' }]  // Turn off bus stations, train stations, etc.
      }],
    });
    var geocoder = new google.maps.Geocoder;
    infoWindow = new google.maps.InfoWindow;
    var chicago = { lat: {{ object.lat }}, lng: {{ object.lon }} };
    var marker = new google.maps.Marker({
      position: chicago,
      map: map,
      title: 'Click to zoom'
    });
  }

  function geocodeLatLng(geocoder, map, infowindow, homer) {
    geocoder.geocode({'location': homer}, function(results, status) {
      if (status === 'OK') {
        if (results[0]) {
          infowindow.setContent(results[0].formatted_address);
          infoWindow.setContent(results[0].formatted_address);
          infoWindow.setPosition(homer);
          infoWindow.open(map);
          map.setCenter(homer);
          map.setZoom(14);
        } else {

        }
      } else {
        window.alert('Falha na requisição: ' + status);
      }
    });
  }
</script>
<script>
  $(document).ready(function () {
    $('select').formSelect();
    $('select.multiselect').show();
    $("select").change(function () {
      getUF($('select').val())
    });
  });

  function getUF(id) {
    $.get(`http://servicodados.ibge.gov.br/api/v1/localidades/estados/${id}/municipios`, function (data) {
      const retorno = data.map(elem => elem.nome);
      var result = {};
      for (var i = 0; i < retorno.length; i++) {
        result[retorno[i]] = null;
      }
      $('input#id_cidade_usuario').autocomplete({
        data: result,
      });
    });
  }

</script>
{% endblock %}

apps/website/templates/evento_confirm_delete.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <title>Direita Unida</title>
</head>
<body>
  <style>
    body{

    }
    form{
      padding: 8em;
      text-align: center;
    }
    h5{
      font-size: 36px;
      font-weight: 500;
    }
    p{
      font-size: 20px;
    }
    button{
      padding: 10px 24px;
      border-radius: 4px;
      font-size: 17px;
      color: red;
      box-shadow: 0px 2px 3px 0px #f00;
      cursor: pointer;
    }
  </style>
  <form method="post">{% csrf_token %}
  <h5>
      Deseja deletar o evento
    </h5>
    <p>"{{ object.titulo }}" ?</p>
    <button type="submit">
      Confirmar
    </button>
  </form>
</body>
</html>

apps/website/templates/noticia-interna.html
{% extends 'components/base.html' %}

{% block content %}
<div class="bg-all">
<div class="row expanded">

<div class="row">
  <div class="col m12 s12">
    <span class="colo-black title-notice">
      <pre class="color-gray"> {{object.criado_em|date:"SHORT_DATE_FORMAT"}}</pre>
    </span>
    <h4 class="title-main">{{object.titulo}}</span></h4>
    <p>
        Compartilhado por: <span>{{object.autor}}</span>
    </p>
    <p>

    </p>
    <div class="center-align">
      <img class="img-inter" src="{{object.imagem}}" alt="" />
    </div>
    <p>
      {{object.noticia|safe}}
    </p>
  </div>
  <div class="col m12 s12">
    <br>
    
    <br>
  </div>

  <div class="row">
    <div class="col m12 s12">
      {% if noticias_list.object_list.count %}
      <h3 class="center-align color-green"><b>Veja mais</b></h3>
      {% for noticia in noticias_list %}
        <div class="col m4 s12 center-align">
          <a href="{% url 'artigo:artigo-interno' noticia.slug %}">
            <img src="{{noticia.imagem.url}}" alt="" srcset="" width="190">
            <p class="mais">{{noticia.titulo}}</p>
          </a>
        </div>
        {% endfor %}
      {% else %}
    
      {% endif %}
    </div>
  </div>

</div>
</div>

</div>
{% endblock %}